# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                  name: Install yarn dependencies
                  command: yarn install
            - run:
                  name: Install JUnit coverage reporter
                  command: yarn add --dev jest-junit
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Build application
                  command: yarn build
            - run:
                  name: ESLint
                  command: |
                      mkdir -p ~/reports
                      yarn lint --format junit --output-file ~/reports/eslint.xml
            - run:
                  name: Run tests
                  command: yarn test --coverage --collectCoverage=true --runInBand --reporters=default --reporters=jest-junit
                  environment:
                      JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: coverage
