# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install JUnit coverage reporter
          command: npm i --no-save jest-junit
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build application
          command: npm run build
      - run:
          name: ESLint
          command: |
            mkdir -p reports/junit
            npm run lint -- --format junit --output-file reports/junit/eslint.xml
      - run:
          name: Run tests
          command: npm test -- --coverage --collectCoverage=true --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage
